version: '3'
services:
    web:
        image: nginx
        volumes:
            - ./.docker/conf/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    php:
        build: .
        restart: always
        volumes:
            - .:/var/www/html
    db:
        image: postgres:10.1
        restart: always
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USERNAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432